### PR TITLE
Update documentation

### PR DESCRIPTION
**Pull request by langfzac**
- Update main docs page
- Update/add docstrings for (most) user-facing functions (ie. `TransitTiming`, `ElementsIC`, etc.)
- Add transit timing to 'Basic Usage' page
- Add a 'Gradients' page to show how to access derivatives of transit times

### CODE REVIEW

**Comment by langfzac** [comment]
This gets us most of the way to completing #73.

**Comment by ericagol** [comment]
I think it would be good to make the example in the documentation match the format of that in the paper;  i.e. include the t0 value in the call (even though it is now deprecated).  As I mentioned, this caused a problem in the documentation which led to the transit times being returned as zeros (since the version of NbodyGradient used didn't yet include the method which drops t0).

**Comment by langfzac** [comment]
Ok, I've added a note on constructors that addresses notational differences in the examples here and in the paper. It explicitly shows the `Integrator` constructor from the paper. I think this is a better option than having a 'deprecated' interface as the example in the documentation.

As for the issue with the docs showing zeros for the transit times, this will be fixed when this is merged. 

@ericagol Let me know if there's anything you'd like to add to the docs before I merge.

**Comment by ericagol** [comment]
Looks good; nice work!

**Pull request merged**
